# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WhitestormJS 3D engine.
email: alexbuzin88@gmail.com
description: > # WhitestormJS is a library which combines Three.js and Cannon.js. It makes WebGL development easy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://whitestormjs.xyz/" # the base hostname & protocol for your site
twitter_username: _alex_buzin
github_username:  sasha240100

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
  hard_wrap: true